import {
  buildClientQuotationRows,
  buildInternalCostingRows,
  buildPiRows,
  type CostedBoqRow
} from "@kf/importers";
import PDFDocument from "pdfkit";

type PdfVariant = "quotation" | "internal" | "pi";

export async function buildClientQuotationPdf(rows: CostedBoqRow[]): Promise<Buffer> {
  return buildPdf("Client Quotation", "Commercial quotation prepared from the priced BOQ.", buildClientQuotationRows(rows), "quotation");
}

export async function buildInternalCostingPdf(rows: CostedBoqRow[]): Promise<Buffer> {
  return buildPdf("Internal Costing", "Internal raw material, factory cost, margin, confidence, and source details.", buildInternalCostingRows(rows), "internal");
}

export async function buildPiPdf(rows: CostedBoqRow[]): Promise<Buffer> {
  return buildPdf("Proforma Invoice", "PI export prepared from the approved quotation pricing.", buildPiRows(rows), "pi");
}

async function buildPdf(title: string, subtitle: string, rows: Record<string, unknown>[], variant: PdfVariant): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const document = new PDFDocument({ margin: 36, size: "A4", bufferPages: true });
    const chunks: Buffer[] = [];

    document.on("data", (chunk: Buffer) => chunks.push(Buffer.from(chunk)));
    document.on("end", () => resolve(Buffer.concat(chunks)));
    document.on("error", reject);

    renderHeader(document, title, subtitle);
    rows.forEach((row, index) => {
      if (document.y > 720) {
        document.addPage();
        renderHeader(document, title, subtitle);
      }
      renderRow(document, row, index, variant);
    });
    renderFooter(document);
    document.end();
  });
}

function renderHeader(document: PDFKit.PDFDocument, title: string, subtitle: string) {
  document.fillColor("#1f2937").font("Helvetica-Bold").fontSize(18).text(title);
  document.moveDown(0.3);
  document.fillColor("#64748b").font("Helvetica").fontSize(9).text(subtitle);
  document.moveDown(0.7);
  document.strokeColor("#d1d5db").moveTo(36, document.y).lineTo(559, document.y).stroke();
  document.moveDown(0.6);
}

function renderRow(document: PDFKit.PDFDocument, row: Record<string, unknown>, index: number, variant: PdfVariant) {
  const name = pick(row, "Product Name", "Description");
  const code = pick(row, "Code");
  const qty = pick(row, "Qty");
  const total = currency(pick(row, "Line Total (INR)", "Amount (INR)"));
  const unitPrice = currency(pick(row, "Unit Price (INR)", "Selling Price (INR)"));

  document.fillColor("#0f172a").font("Helvetica-Bold").fontSize(10).text(`${index + 1}. ${name || "Item"}`, { continued: false });
  document.fillColor("#475569").font("Helvetica").fontSize(8).text(`Code: ${code || "-"}   Qty: ${qty || "-"}   Unit: ${unitPrice}   Total: ${total}`);

  const dimensions = pick(row, "Dimensions");
  const specification = pick(row, "Specification");
  if (dimensions || specification) {
    document.fillColor("#64748b").fontSize(8).text([dimensions && `Dimensions: ${dimensions}`, specification && `Spec: ${specification}`].filter(Boolean).join("   "));
  }

  if (variant === "internal") {
    document.fillColor("#475569").fontSize(8).text(
      `Raw: ${currency(pick(row, "Raw Material (INR)"))}   Factory: ${currency(pick(row, "Factory Cost (INR)"))}   Margin: ${pick(row, "Margin %") || "-"}   Confidence: ${pick(row, "Confidence") || "-"}   Source: ${pick(row, "Source") || "-"}`
    );
    const materials = String(pick(row, "Materials") || "");
    if (materials) document.fillColor("#64748b").fontSize(7).text(materials, { width: 510 });
  }

  document.moveDown(0.45);
  document.strokeColor("#e5e7eb").moveTo(36, document.y).lineTo(559, document.y).stroke();
  document.moveDown(0.45);
}

function renderFooter(document: PDFKit.PDFDocument) {
  const range = document.bufferedPageRange();
  for (let pageIndex = range.start; pageIndex < range.start + range.count; pageIndex += 1) {
    document.switchToPage(pageIndex);
    document.fillColor("#94a3b8").font("Helvetica").fontSize(7).text(`Generated by Kian Falcon Costing Tool | Page ${pageIndex + 1}`, 36, 810, { align: "center", width: 523 });
  }
}

function pick(row: Record<string, unknown>, ...keys: string[]): unknown {
  for (const key of keys) {
    if (row[key] !== undefined && row[key] !== null && row[key] !== "") return row[key];
  }
  return "";
}

function currency(value: unknown): string {
  const amount = Number(value);
  if (!Number.isFinite(amount)) return "-";
  return amount.toLocaleString("en-IN", { maximumFractionDigits: 2 });
}
